/**
 * @file 02-events.contract.ts
 * @description Event taxonomy for Syntra geopolitical events.
 *              Covers both the Warfront read-only events collection and v3
 *              additions for Command-tier modules (M17, M20).
 *              IMMUTABLE FROM IMPLEMENTER AGENTS — changes require a CCR.
 *
 * @version 1.0.0
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Event.kind — canonical event classification enum
// ---------------------------------------------------------------------------

/**
 * Discrete event kinds consumed by the matching engine and alert router.
 * 'sanctions_match' is a v3 addition — generated by M17 Sanctions Engine
 * when a watchlist entity matches a sanctions list entry.
 */
export const EventKindEnum = z.enum([
  'port_disruption',   // Port closures, strikes, congestion, infrastructure damage
  'sanctions',         // New sanctions designation, embargo announcement
  'sanctions_match',   // [v3] Entity in org watchlist matches a sanctions entry
  'regulatory',        // Trade regulation changes, tariff updates, license requirements
  'weather',           // Cyclones, floods, earthquakes affecting logistics
  'geopolitical',      // Armed conflict, coup, border disputes, diplomatic ruptures
  'other',             // Does not fit the above; use sparingly
]);

export type EventKind = z.infer<typeof EventKindEnum>;

// ---------------------------------------------------------------------------
// Event.severity
// ---------------------------------------------------------------------------

export const EventSeverityEnum = z.enum(['critical', 'high', 'medium', 'low', 'info']);
export type EventSeverity = z.infer<typeof EventSeverityEnum>;

// ---------------------------------------------------------------------------
// GeoJSON point — Event.geo
// ---------------------------------------------------------------------------

export const GeoJSONPointSchema = z.object({
  type: z.literal('Point'),
  coordinates: z.tuple([
    z.number().min(-180).max(180),   // longitude
    z.number().min(-90).max(90),     // latitude
  ]),
});

export type GeoJSONPoint = z.infer<typeof GeoJSONPointSchema>;

// ---------------------------------------------------------------------------
// Event.source
// ---------------------------------------------------------------------------

export const EventSourceSchema = z.object({
  url: z.string().url(),
  name: z.string(),
  published_at: z.coerce.date().optional(),
  reliability_score: z.number().min(0).max(1).optional(), // future: M28 Intel Provenance
});

export type EventSource = z.infer<typeof EventSourceSchema>;

// ---------------------------------------------------------------------------
// Full event schema (mirrors Warfront events collection + v3 fields)
// ---------------------------------------------------------------------------

export const EventSchema = z.object({
  _id: z.string(),
  title: z.string(),
  description: z.string(),

  /** Legacy flat location — retained for v1 compatibility. */
  location: z.object({ lat: z.number(), lng: z.number() }),

  /** v3 GeoJSON geometry — preferred by M20 Risk Heatmap for Mapbox queries. */
  geo: GeoJSONPointSchema.optional(),

  country: z.string(),
  country_code: z.string(),
  severity: EventSeverityEnum,

  /** Unstructured string in v1; migrates toward EventKind in v3. */
  event_type: z.string(),

  /** v3 typed kind — set when the matching engine classifies the event. */
  kind: EventKindEnum.optional(),

  sources: z.array(EventSourceSchema),
  occurred_at: z.coerce.date(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date().optional(),
});

export type Event = z.infer<typeof EventSchema>;

// ---------------------------------------------------------------------------
// Sanctions-match event — v3 subtype created by M17
// ---------------------------------------------------------------------------

/**
 * Payload emitted by the M17 Sanctions Engine when it generates a
 * 'sanctions_match' alert. Stored in the alert's event_snapshot.
 */
export const SanctionsMatchEventSchema = z.object({
  matched_entity_id: z.string(),
  matched_entity_name: z.string(),
  list_name: z.enum(['ofac_sdn', 'un_consolidated', 'eu_restricted', 'uk_hmt', 'india_mea']),
  list_version: z.string(),
  match_score: z.number().min(0).max(1),
  matched_entry_name: z.string(),
  matched_entry_programs: z.array(z.string()),
  source_url: z.string(),
  screened_at: z.coerce.date(),
});

export type SanctionsMatchEvent = z.infer<typeof SanctionsMatchEventSchema>;

// ---------------------------------------------------------------------------
// BullMQ internal queue payload (worker ↔ dispatcher)
// ---------------------------------------------------------------------------

export const AlertDispatchJobSchema = z.object({
  alert_id: z.string(),
  org_id: z.string(),
  channels: z.array(z.enum(['email', 'whatsapp', 'webhook'])),
  run_at: z.coerce.date().optional(),   // undefined = dispatch immediately
});

export type AlertDispatchJob = z.infer<typeof AlertDispatchJobSchema>;

// ---------------------------------------------------------------------------
// Severity helpers
// ---------------------------------------------------------------------------

export const SEVERITY_ORDER: Record<EventSeverity, number> = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1,
  info: 0,
} as const;

export function meetsEventSeverityThreshold(
  alertSeverity: EventSeverity,
  threshold: EventSeverity,
): boolean {
  return SEVERITY_ORDER[alertSeverity] >= SEVERITY_ORDER[threshold];
}
